test: enable bucket versioning for remote target for TestAddRemoteBucket and TestDeleteRemoteBucket
 === RUN   TestAddRemoteBucket
targetBucket:  targetbucket
setupBucketForEndpoint(): HTTP Status is in the 2xx range
setupBucketForEndpoint(): HTTP Status is in the 2xx range
    user_api_bucket_test.go:3862:
        	Error Trace:	/home/runner/work/console/console/integration/user_api_bucket_test.go:3862
        	Error:      	Not equal:
        	            	expected: 201
        	            	actual  : 500
        	Test:       	TestAddRemoteBucket
        	Messages:   	Http Response: {"detailedMessage":"error adding remote bucket: The remote target does not have versioning enabled","message":"an error occurred, please try again"}
finalResponse:  Http Response: {"buckets":[{"accessKey":"minioadmin","bandwidth":107374182400,"healthCheckPeriod":60,"remoteARN":"arn:minio:replication::31582283-f6af-4e02-8a05-0d811356bf68:testgetbucketquota","service":"replication","sourceBucket":"testputobjectslegalholdstatus","syncMode":"async","targetBucket":"testgetbucketquota","targetURL":"localhost:9000"}],"total":1}

    user_api_bucket_test.go:3879:
        	Error Trace:	/home/runner/work/console/console/integration/user_api_bucket_test.go:3879
        	Error:      	Not equal:
        	            	expected: false
        	            	actual  : true
        	Test:       	TestAddRemoteBucket
--- FAIL: TestAddRemoteBucket (0.08s)
=== RUN   TestDeleteRemoteBucket
targetBucket:  targetbucket2
setupBucketForEndpoint(): HTTP Status is in the 2xx range
setupBucketForEndpoint(): HTTP Status is in the 2xx range
    user_api_bucket_test.go:3921:
        	Error Trace:	/home/runner/work/console/console/integration/user_api_bucket_test.go:3921
        	Error:      	Not equal:
        	            	expected: 201
        	            	actual  : 500
        	Test:       	TestDeleteRemoteBucket
        	Messages:   	Http Response: {"detailedMessage":"error adding remote bucket: The remote target does not have versioning enabled","message":"an error occurred, please try again"}
    user_api_bucket_test.go:3934:
        	Error Trace:	/home/runner/work/console/console/integration/user_api_bucket_test.go:3934
        	Error:      	Not equal:
        	            	expected: 200
        	            	actual  : 500
        	Test:       	TestDeleteRemoteBucket
        	Messages:   	Http Response:
    user_api_bucket_test.go:3950:
        	Error Trace:	/home/runner/work/console/console/integration/user_api_bucket_test.go:3950
        	Error:      	No remote arn response
        	Test:       	TestDeleteRemoteBucket
--- FAIL: TestDeleteRemoteBucket (0.07s)